### PR TITLE
Update df creation in helper function

### LINKED ISSUE #63: Pandas deprecation FutureWarning for convert_dtype
Using `bletl.parse(raw_data)` generates the following `FutureWarning`:
```
/path/to/bletl/utils.py:38: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  dfout[ncol] = dfin[ocol].apply(lambda x: typ(x), convert_dtype=False)
```
```
pandas==2.2.1
bletl==1.4.1
```
Thanks very much!

### PR DESCRIPTION
**Pull request by rebeccahamel**
Closes #63

### CODE REVIEW

**Comment by rebeccahamel** [comment]
recheck

**Comment by rebeccahamel** [comment]
- [x] The JuBiotech maintainers know my real name.

At least one of the following two applies:

- [x] The JuBiotech maintainers know my current employer.

- [ ] I am *not* making this contribution on behalf of my current employer.

**Comment by rebeccahamel** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Review by michaelosthege — APPROVED** [review]
A small diff for a PR, a giant leap for a warning-free `bletl` experience!

**Pull request merged**
